apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: artyom366/multi-server
          ports:
            - containerPort: 5000 #inside image port   
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service #cluster ip service name
            - name: REDIS_PORT
              value: '6379' #outside post in redis-cluster-ip-service
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-id-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD #name of the env used inside of container
              valueFrom:
                  secretKeyRef:
                      name: pgpassword #name of the secret
                      key: PGPASSWORD #key of the secret             